name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Diese Jobs werden automatisch bei einem Push auf den "main"-Branch ausgeführt
  workflow_dispatch:  # Ermöglicht das manuelle Triggern für den "destroy"-Job

jobs:
  init:
    name: Terraform Init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: init  # Dieser Job wird automatisch nach init ausgeführt
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Plan
      run: terraform plan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan  # Dieser Job wird automatisch nach plan ausgeführt
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Apply
      run: terraform apply -auto-approve

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Dieser Job kann nur manuell getriggert werden
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Plan Destroy
      run: terraform plan -destroy

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
